# Generated by Django 3.2.23 on 2023-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookpedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
